import type { Tenant, TenantSettings } from '@/types'

// Demo tenants for testing multi-tenancy
export const DEMO_TENANTS: Record<string, Tenant> = {
  'fbc': {
    id: 'fbc-001',
    name: 'Fourah Bay College',
    slug: 'fbc',
    type: 'COLLEGE',
    logo_url: '/logos/fbc.png',
    primary_color: '#1a56db',
    secondary_color: '#7c3aed',
    address: '123 Siaka Stevens Street',
    city: 'Freetown',
    country: 'Sierra Leone',
    phone: '+232 22 123456',
    email: 'info@fbc.edu.sl',
    website: 'https://fbc.edu.sl',
    subscription_plan: 'PROFESSIONAL',
    subscription_status: 'ACTIVE',
    status: 'ACTIVE',
    max_students: 2000,
    max_staff: 200,
    storage_limit_gb: 50,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  'usl': {
    id: 'usl-001',
    name: 'University of Sierra Leone',
    slug: 'usl',
    type: 'UNIVERSITY',
    logo_url: '/logos/usl.png',
    primary_color: '#059669',
    secondary_color: '#0891b2',
    address: 'Mount Aureol',
    city: 'Freetown',
    country: 'Sierra Leone',
    phone: '+232 22 234567',
    email: 'info@usl.edu.sl',
    website: 'https://usl.edu.sl',
    subscription_plan: 'ENTERPRISE',
    subscription_status: 'ACTIVE',
    status: 'ACTIVE',
    max_students: 10000,
    max_staff: 500,
    storage_limit_gb: 200,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  'njala': {
    id: 'njala-001',
    name: 'Njala University',
    slug: 'njala',
    type: 'UNIVERSITY',
    logo_url: '/logos/njala.png',
    primary_color: '#dc2626',
    secondary_color: '#ea580c',
    address: 'Njala Campus',
    city: 'Bo',
    country: 'Sierra Leone',
    phone: '+232 32 345678',
    email: 'info@njala.edu.sl',
    website: 'https://njala.edu.sl',
    subscription_plan: 'PROFESSIONAL',
    subscription_status: 'ACTIVE',
    status: 'ACTIVE',
    max_students: 5000,
    max_staff: 300,
    storage_limit_gb: 100,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  'demo': {
    id: 'demo-001',
    name: 'Demo University',
    slug: 'demo',
    type: 'UNIVERSITY',
    primary_color: '#6366f1',
    secondary_color: '#8b5cf6',
    country: 'Sierra Leone',
    subscription_plan: 'PROFESSIONAL',
    subscription_status: 'ACTIVE',
    status: 'ACTIVE',
    max_students: 2000,
    max_staff: 200,
    storage_limit_gb: 50,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
}

export const DEMO_SETTINGS: TenantSettings = {
  id: 'demo-settings-id',
  tenant_id: 'demo-tenant-id',
  academic_year_start_month: 9,
  grading_scale: {
    name: 'Standard GPA',
    grades: [
      { letter: 'A', min_score: 70, max_score: 100, grade_point: 4.0, description: 'Excellent' },
      { letter: 'B', min_score: 60, max_score: 69, grade_point: 3.0, description: 'Very Good' },
      { letter: 'C', min_score: 50, max_score: 59, grade_point: 2.0, description: 'Good' },
      { letter: 'D', min_score: 45, max_score: 49, grade_point: 1.0, description: 'Pass' },
      { letter: 'F', min_score: 0, max_score: 44, grade_point: 0.0, description: 'Fail' },
    ],
  },
  currency: 'SLL',
  timezone: 'Africa/Freetown',
  date_format: 'DD/MM/YYYY',
  semester_system: 'SEMESTER',
  allow_online_applications: true,
  allow_online_payments: true,
  require_admission_approval: true,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: new Date().toISOString(),
}

export function getDemoTenant(slug: string): Tenant | null {
  return DEMO_TENANTS[slug] || null
}

export function getAllDemoTenants(): Tenant[] {
  return Object.values(DEMO_TENANTS)
}
